### ISSUE TITLE
reindex understanding

### ISSUE THREAD

**Issue by becker-IT** [codelibs/elasticsearch-reindexing#11]
Hi,

a stupid question probably, but is there any pre-condition I don't match? 

` ` ` 
curl -XPOST localhost:9100/logstash-2015.09.08/_reindex/logstash-2015.08.30_v1/
{"error":"InvalidTypeNameException[mapping type name [_reindex] can't start with '_']","status":400}
` ` ` 
` ` ` 
curl -XPOST localhost:9100/logstash-2015.09.08/logstash-2015.08.30_v1/
{"error":"MapperParsingException[failed to parse, document is empty]","status":400}
` ` ` 

I just like to re-index all my old indices, as I understand I have to create a new index build from the latest one and alias the old index to the new index. But how I get a "_reindex"?

confused...

**Comment by marevol** [comment]
Could you check if reindexing plugin is installed?
https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-plugins.html

**Comment by becker-IT** [comment]
Oh, it seems I missed a restart of ES! 

Now I got the plugin two times, I guess I had to install it on one node only...
```
curl localhost:9100/_cat/plugins?v
name                  component        version type url 
prd02-es-02 ReindexingPlugin 1.7.0   j        
prd01-es-01 ReindexingPlugin 1.7.0   j   
```

The second node is not starting any more: 
```
[WARN ][index.mapper             ] [prd02-es-02] [logstash-2015.09.08] Type [logstash-2015.08.30_v1] contains a '.', it is recommended not to include it within a type name
```
