### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shaharmor** [codelibs/elasticsearch-reindexing#13]
Hi,

After running this command on ES1.5.2:
`./bin/plugin -i org.codelibs/elasticsearch-reindexing/2.1.0`

the XGET command is returning:
```
curl -XGET localhost:9200/_reindex
{"error":"ElasticsearchIllegalArgumentException[No feature for name [_reindex]]","status":400}
```

but it is installed:
```
./bin/plugin -l
Installed plugins:
    - reindexing
```

**Comment by marevol** [comment]
Could you try 1.4.4 or 1.7.1?
2.1.0 does not work on ES 1.x.

**Comment by shaharmor** [comment]
I think it was a permissions bug
