### ISSUE TITLE
Send reindexing data to a remote host

### ISSUE THREAD

**Issue by marevol** [codelibs/elasticsearch-reindexing#2]

**Comment by xmudall** [comment]
It's not working for me. I've 2 clusters with 3 nodes for each and i've installed this plugin for all 6 nodes. I can do a post request successfully to http://host1:9200/index1/_reindex/index2/?url=http%3A%2F%2Fhost2%3A9200%2F, and get correct response with a name. After some time the process seems finished from -XGET http://host1:9200/_reindex API, but nothing changed to the host2

**Comment by marevol** [comment]
Check Elasticsearch's log file and open a new issue with more details.
