### ISSUE TITLE
How do you pass your custom query ?

### ISSUE THREAD

**Issue by MrHypnos** [codelibs/elasticsearch-reindexing#8]
The plugin works great but I cannot make it work with my custom query.
I had a look at the source code and it does take the content of the request if not null.
Here is my query for example: 

curl -XPOST localhost:9200/oldindex/type/_reindex/newindex/type -d '{ "query": { "match": { "myField" : "test" }}}'

**Comment by yoitsro** [comment]
This would be *really* useful.
